name: BiomeGifts
version: 1.0-SNAPSHOT
main: com.biomegifts.BiomeGifts
api-version: 1.21
authors: [TraeAI]
description: A plugin that adds biome-specific gifts and crop growth modifiers.
commands:
  getgift:
    description: 获取地域馈赠物品
    usage: /getgift <item>
    permission: biomegifts.admin
permissions:
  biomegifts.admin:
    description: 允许使用管理指令
    default: op
